#!/bin/bash
#
# simple script to emit sed rules to individually filter out each group listed as a group title.
# The expected use is to run this when you initially get an M#U and pipe the output to a file with a '.sed'
# then remove the groups you want to keep, either manually or using your own script.
# then you can use the .sed file to cut out the unwanted groups, e.g. like
#
# m3upipe < my.m3u | sed -f my.sed

sed -n -e 's/.*group-title="\([^"]*\).*$/\/group-title="\1"\/ d/ p' "$1" | sort --unique
